version: '3'
services:
  notebook:
    #containernameは付けた方が便利
    container_name: wanimaenv
    build: .
    #https://qiita.com/y518gaku/items/456f34c317a65a9dae86
    volumes:
      - ./src:/usr/src
    tty: true

