
#define WANIMA1 "                  ,fVo)                                                                .\n"
#define WANIMA2 "  ...             .FG6O.    -\n"
#define WANIMA3 ",(Jp\1             bOVWh                               .                                                                                                                                               `\n"
#define WANIMA4 " ?!<?`             1XNoW|      ......                                                                    .\n"
#define WANIMA5 "                    NdBdF.,?=?!```     `_!-.\n"
#define WANIMA6 "                    NNMM`              .~-. ?i.                                                                                                                                                        `\n"
#define WANIMA7 "    `_              MMMb               ^??{`(, 7,                                                                                                     \n"
#define WANIMA8 "       !   `        MkMN|                 _?<.?- ?+        ...__?7z?i.                          ,      ..                   .                    `,   \n"
#define WANIMA9 "                    JMMMN                          T...J7!` ..?!    .?n.              `      . `> <.,`-,!  .,.`.                     `                         `\n"
#define WANIMA10 "                 ..JY?7'M{                     ..-/7!     .-^      !. ,h             .>      `?nvzdx,.IH../iu-<-_                                     \n"
#define WANIMA11 "           ..JY9'`      j]                 ..J7!        .J3>         .:d     `       .S. .T'<,?ZYX9HRXvwMn?JcY-l.,.                                         `\n"
#define WANIMA12 "     ..-VM8!            ,]     ~_      ..(7`          (+01;         .',=     !.-..  ...d+.,+1ii+JZmWAVfXYiJ5..,?<Tv``..:                              \n"
#define WANIMA13 "..Q'8OGJ~zC_            ,]          ..?`        .  ..1+Wz>       ._i(=     .!??71S,>(,?7TQQ&?YOHWZzuUi+JY1x(dZUC-((Y7<-..                             \n"
#define WANIMA14 "zWZXZ4xuJ<~`            ,>       (/^            ..7!!   4      .-''        ~ .    7oJu&zzOjvwzSW4XMGe&XWBCCJSkJk&Gy9AS&.6_                                 `\n"
#define WANIMA15 "NQkHHXNf!               ._    .(^          ...ZY?`      .L..7=             ~j+~<(~-j...ZdGdX=whVwwHVUJGc7jdk8.(dHXHSGuQgHl.`                          \n"
#define WANIMA16 "MMdU(B^        ..gm+J...J`  .?`    ....JvT'^`          - (.                >_?o??UZXWkV8&wmd51.+dSWkzdGghyOXjmH9n?jkHmgHgW$~i.                        \n"
#define WANIMA17 "H#Vvf    .JT'''''''''YHMM$ .J..JymHHF       .dMMMNQmJ.d`.JM]           `    .l_zdk&.JXdkXHhAugWedVWT9WMHv9uHWd9zbJWXJVWNHSXdM^.                           `\n"
#define WANIMA18 "HHM?`           ...( .?` .MMBj86MWf]     (9""!`    (C` (i.]             `_<(+1z<..J(XWWkHHHM49OjdVVXUXgHH#6&8CvZ`` ??77TR?NX<                         \n"
#define WANIMA19 "XXN>         ?=!`,M' 9(JdMM5uKN_4R[.         .._!! ,c` .2X!    .       ...+?jz--<(JWdHmHkhx&YUdWkH#mdMf1?3vI$(^          4MW1l                          \n"
#define WANIMA20 "SWf         . (7CJN. (NHMM>1HHHG-?6         `..vWMM['   .W             . __(J+JJjgdkkakGdWHwHH8dYKOAd=J+?j>.`             4K:3                            \n"
#define WANIMA21 "kU`              ?T!  WUH/jJdMHmdl.         .  ..V'=,.   .l            ?-.(I(wagVTWO9XHUH0CiJmwAJZz^.=<(7`                 4,.                      \n"
#define WANIMA22 "Sc.               _   ,NGAWNMdHXC           .!     .!      <.            ?.,iJ&+1jdWQK5z4WMMMM9dd?+CR?`     .               2.                      \n"
#define WANIMA23 "@>                     Jw#XdXdHM[                 ~         ..             ?6i..-HWHHdGTdH6SHK(yj11^         ...            <`                      \n"
#define WANIMA24 "K!      `               Sj,WKOMW>                     .   ...>             (J/~CZKZOZTY-6<,THTV/((!       .JWWMMMMNg(.   .+HN                       \n"
#define WANIMA25 "6`       <              .vi>7Q'?             .        `jv'CQ,           (?</vWUzXfz1+J''<<7Tflj_`_               ?UMl  _M'=!]                       \n"
#define WANIMA26 "+- `                     J?( ~_.                        .dXHm-              v1J<dkzj>.7(Jj?1JS/`           .J7'Qg-.?>  d>...!                       \n"
#define WANIMA27 "__~              d...-zT''  i _?-.                   .AB>^ ..;             .v+((d6dd.>.v.[(zdd`            ....HM}.    X~MF!                        \n"
#define WANIMA28 "  `..            0vUM,. .MMMNb   _.                 .dY!.xqH8             .?C?99VHdJ,/It.]d&X_^           `     ^`3    .: ..                        \n"
#define WANIMA29 "             `  !  d,WHdMMMMMNh.          `            7! ...!              _1+XH@(dL((y<1,?U-..                        (..`                        \n"
#define WANIMA30 "                   .hBYhdMMNMYXN,     `                 .7HM8>          `...(+J+dJjHdb((V5Jn.[  -                        (,                          \n"
#define WANIMA31 "                 .#BHNmNNkWF   TJh,                        ,`      `..?!      .T1n+?ZsJ1....Jb                    .. .(.. z                          \n"
#define WANIMA32 "!          `   (""E  7HNMMM)     .7k,             `       .Wh.    ./  ..(gma+gagNMNedMqNNK~! q.                   ,7777?!7F    .`                    \n"
#define WANIMA33 "x.          ..++gH^     ?Wm'     _- ~HWa(.. `            .q@@j.  .^   /MMMMMMMMMMMMNMNNMN@    b                      ..(Ja{                           \n"
#define WANIMA34 "Zs            qH6.         ?i.     _  ?XXWSdWXO+(...(...QN#Ek>!`.!     ,MMMMMMMMMMMMMMMNdW    -[                 .(kY=<..,$                           \n"
#define WANIMA35 "Wv:-.         MRMc           (1,    `   ,TVTZHNMMMB''7WWW93/=  ,`  .    .WMMMM#MMMMMMMNMWH`    G.               J$-(777??T                            \n"
#define WANIMA36 "JH>UA.   `  .dMMNr-.  .        .4,   (.    ?z4HK, 4       `   ,'    .     TMNMMMNMMMMMMMNN      h                   ....-2                            \n"
#define WANIMA37 "MXH0HV.(.j(,KNMqd] (4a,_`.?_.     =,         `dHHh 1         ,!     ..     (HMM#MMMMMMMMMM       G,                 `7?TW!    .                       \n"
#define WANIMA38 "MMMqMGMgQHqMMdMgv`    .'z(<_-.      ?,       .Md<~l.[       .>       ..     .WkHNMMMMMMM#@_       ?,                   (c                      .`     \n"
#define WANIMA39 "MMMMMNMMNMMNdWkMWNm,      ?G.         ~.   ..JH+` ,>(       s     _   ..      7HgWMMMMMYDP         .4+.     .        . (>j,                           \n"
#define WANIMA40 "MMNMMMMMNMM@HJN$  ?4Jm,    i.!.        .,   .MR>  .).{     .>           ~.      7Qd@^  ,{>           ?dXa.,  `..(,...+q$,:,~.                         \n"
#define WANIMA41 "MMMMNMNMMMEkMY=  +g.dwMMNJ, 1(<<         4, .H0`   X (.    k       ~!    ~1.     .7kwi. .`             ??WNHkaa.a(JggMNgh(F.,~                        \n"


#define OTAKU1 "                                                                .\n"
#define OTAKU2 "  \n"
#define OTAKU3 "                             .                                                                                                                                               `\n"
#define OTAKU4 "                                                                .\n"
#define OTAKU5 "  \n"
#define OTAKU6 "                                                                                                                                              `\n"
#define OTAKU7 "                                 ..J(+QNNMMMNMNMMMMNMm,\n"
#define OTAKU8 "                 `,          .JNMMMMMMMMMMMMyHdNzTdHNRdNg,.\n"
#define OTAKU9 "     `                     ,TNMMMMMMMMWWYH8o(OhydgJHHMMMMMMMHa         `\n"
#define OTAKU10 "                          .dMMNM#BBUW?1&+HNHWMMNMMMMMMMMMMMMMNQ.\n"
#define OTAKU11 "                        .dMMMM6XAJmJ(xNgNMMMMNMMMMMMMMMMMMMMMMMN,      `\n"
#define OTAKU12 "                       ,MMMUUjWNKMHMgMMMMMMMMMMMMMMMMMMMMMMMMMMNN\n"
#define OTAKU13 "                      .dMW1WNMHWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM[\n"
#define OTAKU14 "                       #KkKHMMMd#MNdMdMMMMNMMNMMMMMMMMMMMMMMMMMMM@     `\n"
#define OTAKU15 "                      .MHMKdUM9J@Y#R?drT#dMXJNMMMMMMMMMMMMMMMMMMM#.\n"
#define OTAKU16 "                      .9WM@d.H>d@ z$ jt W0MK2MH+MMMMMMMMMMMMMMMM#N)\n"
#define OTAKU17 "                       .ydMUE H`(@ ,F ({ ,r(]~d?</SHMNNMMMMMMMMMMMM]    `\n"
#define OTAKU18 "                       fMH(= .  E .! .!..!   `  `?9MMMNMMMMMMMMMMN> \n"
#define OTAKU19 "                        ?$ `    ..+NMNHMMm,       _WMMMMMMMMMMMMMN> \n"
#define OTAKU20 "                        .MMNe  .MB!.....,._'       _dMMMMMMMMMMMMF     `\n"
#define OTAKU21 "                    `  ..../B, .Kr....,.,,D<d9VTTO1z+TMHMMMMMMMMN'\n"
#define OTAKU22 "                     y-.,zNtNWH#?>  TM5...FkOzI<?7?7TXgmgMMY` ,MF      `\n"
#define OTAKU23 "                     EdMM&v!d?Zdp: !   ..Y!          (WMMPj7>([.,\n"
#define OTAKU24 "                     ?2  h.d' ?` Y7'''7`             ?WMHK?h,-[ >\n"
#define OTAKU25 "                        .p<C     .           .`      (NMM+XP/,`.`      `\n"
#define OTAKU26 "                        .#(`  `  ,                   -NM#Zl?,~,!\n"
#define OTAKU27 "                         #?NKH&uZWn.                 ,MM#77`.7         `\n"
#define OTAKU28 "                         W(MB.`      '             .` ~(_=s=       .\n"
#define OTAKU29 "                         ,J'.`                    .~   r  X`\n"
#define OTAKU30 "                          jQdNmgx...                  ,`  #            `\n"
#define OTAKU31 "                           HXWANIMA`                 ('   @\n"
#define OTAKU32 "`                           7NNmHHD            .  .,T^    U            `\n"
#define OTAKU33 "                      .      .M`            .(.~.7^ .     J,\n"
#define OTAKU34 "                               5,        ..eggY^    `     ,b           `\n"
#define OTAKU35 "                                .'4WA&ggWMH87!     `      .dMH&\n"
#define OTAKU36 "                                      d@wZC!               ?dNXWma     `\n"
#define OTAKU37 "                                  ..&MMD(:                  dHXHHkH,\n"
#define OTAKU38 "               .`            ..dMMMMMMMb!                 .dWHNMHuzWe  `\n"
#define OTAKU39 "                         `.dHHWWWXUXWHM]        ~       .dWWHMMHHXzzVN,\n"
#define OTAKU40 "                         .BXXXWXuzzzXdM!      .-     .J8qHHWHXWWKHkzzzH[\n"
#define OTAKU41 "                       `.BzuXXUzXzzzXN$     .!   ..dSuqHWWUUzzzuXWWHkkzI\n"

#define WANIOTA1 "                     ,fVo)                                                                .\n"
#define WANIOTA2 "     ...             .FG6O.    -\n"
#define WANIOTA3 "   ,(Jp\1             bOVWh                               .                                                                                                                                             \n"
#define WANIOTA4 "    ?!<?`             1XNoW|      ......                                                                  \n"
#define WANIOTA5 "                       NdBdF.,?=?!```     `_!-.\n"
#define WANIOTA6 "                       NNMM`              .~-. ?i.                                                                                                                                                      \n"
#define WANIOTA7 "       `_              MMMb               ^??{`(, 7,                                                                                                                ..J(+QNNMMMNMNMMMMN\n"
#define WANIOTA8 "          !   `        MkMN|                 _?<.?- ?+        ...__?7z?i.                          ,      ..                   .                    `,          .JNMMMMMMMMMMMMyHdNzTdHNRdN\n"
#define WANIOTA9 "                       JMMMN                          T...J7!` ..?!    .?n.              `      . `> <.,`-,!  .,.`.                     `                     ,TNMMMMMMMMWWYH8o(OhydgJHHMMMMMM         `\n"
#define WANIOTA10 "                    ..JY?7'M{                     ..-/7!     .-^      !. ,h             .>      `?nvzdx,.IH../iu-<-_                                         .dMMNM#BBUW?1&+HNHWMMNMMMMMMMMMMMMM\n"
#define WANIOTA11 "              ..JY9'`      j]                 ..J7!        .J3>         .:d     `       .S. .T'<,?ZYX9HRXvwMn?JcY-l.,.                                     .dMMMM6XAJmJ(xNgNMMMMNMMMMMMMMMMMMMMMM      `\n"
#define WANIOTA12 "        ..-VM8!            ,]     ~_      ..(7`          (+01;         .',=     !.-..  ...d+.,+1ii+JZmWAVfXYiJ5..,?<Tv``..:                               ,MMMUUjWNKMHMgMMMMMMMMMMMMMMMMMMMMMMMMM\n"
#define WANIOTA13 "   ..Q'8OGJ~zC_            ,]          ..?`        .  ..1+Wz>       ._i(=     .!??71S,>(,?7TQQ&?YOHWZzuUi+JY1x(dZUC-((Y7<-..                             .dMW1WNMHWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
#define WANIOTA14 "   zWZXZ4xuJ<~`            ,>       (/^            ..7!!   4      .-''        ~ .    7oJu&zzOjvwzSW4XMGe&XWBCCJSkJk&Gy9AS&.6_                             #KkKHMMMd#MNdMdMMMMNMMNMMMMMMMMMMMMMMMMM     `\n"
#define WANIOTA15 "   NQkHHXNf!               ._    .(^          ...ZY?`      .L..7=             ~j+~<(~-j...ZdGdX=whVwwHVUJGc7jdk8.(dHXHSGuQgHl.`                          .MHMKdUM9J@Y#R?drT#dMXJNMMMMMMMMMMMMMMMMMM\n"
#define WANIOTA16 "   MMdU(B^        ..gm+J...J`  .?`    ....JvT'^`          - (.                >_?o??UZXWkV8&wmd51.+dSWkzdGghyOXjmH9n?jkHmgHgW$~i.                        .9WM@d.H>d@ z$ jt W0MK2MH+MMMMMMMMMMMMMMMM\n"
#define WANIOTA17 "   H#Vvf    .JT'''''''''YHMM$ .J..JymHHF       .dMMMNQmJ.d`.JM]           `    .l_zdk&.JXdkXHhAugWedVWT9WMHv9uHWd9zbJWXJVWNHSXdM^.                        .ydMUE H`(@ ,F ({ ,r(]~d?</SHMNNMMMMMMMMMM    `\n"
#define WANIOTA18 "   HHM?`           ...( .?` .MMBj86MWf]     (9""!`    (C` (i.]             `_<(+1z<..J(XWWkHHHM49OjdVVXUXgHH#6&8CvZ`` ??77TR?NX<                          fMH(= .  E .! .!..!   `  `?9MMMNMMMMMMMMM \n"
#define WANIOTA19 "   XXN>         ?=!`,M' 9(JdMM5uKN_4R[.         .._!! ,c` .2X!    .       ...+?jz--<(JWdHmHkhx&YUdWkH#mdMf1?3vI$(^          4MW1l                          ?$ `    ..+NMNHMMm,       _WMMMMMMMMMMMM \n"
#define WANIOTA20 "   SWf         . (7CJN. (NHMM>1HHHG-?6         `..vWMM['   .W             . __(J+JJjgdkkakGdWHwHH8dYKOAd=J+?j>.`             4K:3                          .MMNe  .MB!.....,._'       _dMMMMMMMMMM     `\n"
#define WANIOTA21 "   kU`              ?T!  WUH/jJdMHmdl.         .  ..V'=,.   .l            ?-.(I(wagVTWO9XHUH0CiJmwAJZz^.=<(7`                 4,.                      `  ..../B, .Kr....,.,,D<d9VTTO1z+TMHMMMMMM'\n"
#define WANIOTA22 "   Sc.               _   ,NGAWNMdHXC           .!     .!      <.            ?.,iJ&+1jdWQK5z4WMMMM9dd?+CR?`     .               2.                       y-.,zNtNWH#?>  TM5...FkOzI<?7?7TXgmgMMY`       `\n"
#define WANIOTA23 "   @>                     Jw#XdXdHM[                 ~         ..             ?6i..-HWHHdGTdH6SHK(yj11^         ...            <`                       EdMM&v!d?Zdp: !   ..Y!          (WMMPj7>(\n"
#define WANIOTA24 "   K!      `               Sj,WKOMW>                     .   ...>             (J/~CZKZOZTY-6<,THTV/((!       .JWWMMMMNg(.   .+HN                        ?2  h.d' ?` Y7'''7`             ?WMHK?h >\n"
#define WANIOTA25 "   6`       <              .vi>7Q'?             .        `jv'CQ,           (?</vWUzXfz1+J''<<7Tflj_`_               ?UMl  _M'=!]                           .p<C     .           .`      (NMM+XP/,      `\n"
#define WANIOTA26 "   +- `                     J?( ~_.                        .dXHm-              v1J<dkzj>.7(Jj?1JS/`           .J7'Qg-.?>  d>...!                           .#(`  `  ,                   -NM#Zl?,\n"
#define WANIOTA27 "   __~              d...-zT''  i _?-.                   .AB>^ ..;             .v+((d6dd.>.v.[(zdd`            ....HM}.    X~MF!                             #?NKH&uZWn.                 ,MM#77         `\n"
#define WANIOTA28 "     `..            0vUM,. .MMMNb   _.                 .dY!.xqH8             .?C?99VHdJ,/It.]d&X_^           `     ^`3    .: ..                             W(MB.`      '             .` ~(_       .\n"
#define WANIOTA29 "                `  !  d,WHdMMMMMNh.          `            7! ...!              _1+XH@(dL((y<1,?U-..                        (..`                             ,J'.`                    .~   r \n"
#define WANIOTA30 "                      .hBYhdMMNMYXN,     `                 .7HM8>          `...(+J+dJjHdb((V5Jn.[  -                        (,                               jQdNmgx...                  ,`            `\n"
#define WANIOTA31 "                    .#BHNmNNkWF   TJh,                        ,`      `..?!      .T1n+?ZsJ1....Jb                    .. .(.. z                                HXWANIMA`                 (' \n"
#define WANIOTA32 "   !          `   (""E  7HNMMM)     .7k,             `       .Wh.    ./  ..(gma+gagNMNedMqNNK~! q.                   ,7777?!7F    .`                           7NNmHHD            .  .,T^              `\n"
#define WANIOTA33 "   x.          ..++gH^     ?Wm'     _- ~HWa(.. `            .q@@j.  .^   /MMMMMMMMMMMMNMNNMN@    b                      ..(Ja{                           .      .M`            .(.~.7^ .    \n"
#define WANIOTA34 "   Zs            qH6.         ?i.     _  ?XXWSdWXO+(...(...QN#Ek>!`.!     ,MMMMMMMMMMMMMMMNdW    -[                 .(kY=<..,$                                    5,        ..eggY^    `               `\n"
#define WANIOTA35 "   Wv:-.         MRMc           (1,    `   ,TVTZHNMMMB''7WWW93/=  ,`  .    .WMMMM#MMMMMMMNMWH`    G.               J$-(777??T                                      .'4WA&ggWMH87!     `      .d\n"
#define WANIOTA36 "   JH>UA.   `  .dMMNr-.  .        .4,   (.    ?z4HK, 4       `   ,'    .     TMNMMMNMMMMMMMNN      h                   ....-2                                            d@wZC!               ?dNX     `\n"
#define WANIOTA37 "   MXH0HV.(.j(,KNMqd] (4a,_`.?_.     =,         `dHHh 1         ,!     ..     (HMM#MMMMMMMMMM       G,                 `7?TW!    .                                   ..&MMD(:                  dHXHH\n"
#define WANIOTA38 "   MMMqMGMgQHqMMdMgv`    .'z(<_-.      ?,       .Md<~l.[       .>       ..     .WkHNMMMMMMM#@_       ?,                   (c                      .`            ..dMMMMMMMb!                 .dWHNMHu  `\n"
#define WANIOTA39 "   MMMMMNMMNMMNdWkMWNm,      ?G.         ~.   ..JH+` ,>(       s     _   ..      7HgWMMMMMYDP         .4+.     .        . (>j,                              `.dHHWWWXUXWHM]        ~       .dWWHMMHHXzz\n"
#define WANIOTA40 "   MMNMMMMMNMM@HJN$  ?4Jm,    i.!.        .,   .MR>  .).{     .>           ~.      7Qd@^  ,{>           ?dXa.,  `..(,...+q$,:,~.                            .BXXXWXuzzzXdM!      .-     .J8qHHWHXWWKHkzz\n"
#define WANIOTA41 "   MMMMNMNMMMEkMY=  +g.dwMMNJ, 1(<<         4, .H0`   X (.    k       ~!    ~1.     .7kwi. .`             ??WNHkaa.a(JggMNgh(F.,~                         `.BzuXXUzXzzzXN$     .!   ..dSuqHWWUUzzzuXWWHk\n"